#! /bin/sh

sxhkd &
xrdb ~/.Xresources

# got this one from papers.co
wal -i /home/dramalama/Pictures/wavepattern4k.jpg --saturate 0.4

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DVI-I-1 -d I II III IV
bspc monitor HDMI-1 -d V VI VII VIII
#bspc monitor HDMI-2 -d IX

color=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)

bspc config focused_border_color "#$color"
bspc config normal_border_color  "#$color2"

bspc config border_width         5
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#feh --bg-fill /home/dramalama/Pictures/wallhaven-751167.jpg

nohup compton &
nohup conky &
